language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
os:
  - linux
  - osx
  - windows
node_js:
  - '8'

stages:
  - before_install
  - install
  - after_success

jobs:
  include:
    - stage: install
      script:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install nodejs; fi
    - stage: before_install
      script:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install nodejs; fi
    - stage: after_success
      script:
        - npm run travis-deploy-once "npm run report-coverage"
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run deploy-docs; fi
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run semantic-release; fi

branches:
  except:
    - /^v\d+\.\d+\.\d+$/